### ISSUE TITLE
Get title of windows via specific process

### ISSUE THREAD

**Issue by Milo123459** [HiruNya/window_titles#1]
Hi! Great crate, thanks for making.

I was wondering, if possible, could you add a way to get the title of windows from a specific process? ie spotify.exe

So, find windows of spotify.exe, return a vec of windows with the titles. Thanks!

**Comment by HiruNya** [comment]
Hi, thanks for taking a look at our crate.

That's a pretty interesting request and I'll definitely try and take a look at it when I can. I'm a tad bit busy this week but hopefully I'll have some time.

I just have a few questions for your use case:
- Since you use `exe` in your title, can I assume your main use case is Windows?
- Do you want to search by file name (e.g. spotify.exe)? The full path (e.g.C:/Users/Hiru/spotify.exe)? Or the process id?

I did some quick googling and so I'll put this here so that I can come back to it when I need it
- https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-processes
- https://docs.microsoft.com/en-us/windows/win32/api/Psapi/nf-psapi-enumprocesses
- https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulebasenamew
- https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowthreadprocessid

**Comment by Milo123459** [comment]
Hi! 

I want this for windows, but as always, cross platform is good! 

And what I mean is, find the process spotify.exe, list the windows, and return the titles as a vec

**Comment by HiruNya** [comment]
> I want this for windows, but as always, cross platform is good!

I fully intend on trying to support all platforms but now I can prioritise Windows first.

(btw @Techno-coder I'd like you to look into seeing if this can be done on OSX if you have the time)

**Comment by Milo123459** [comment]
Thank you!

**Comment by Milo123459** [comment]
Have we got an eta? I'll help however I can

**Comment by Milo123459** [comment]
^^ also maybe publish to crates?

**Comment by HiruNya** [comment]
Sorry, I had a busy week and only managed to allocate some time for this tonight.

I made a quick minimal version of this in the [process-support](https://github.com/HiruNya/window_titles/tree/process-support) branch.

This should support something like this:
```rust
use window_titles::{Connection, ConnectionTrait};

fn main() {
	let connection = Connection::new().unwrap();
	connection.windows().into_iter().filter(|w| w.process().name() == "Spotify.exe")
		.for_each(|x| println!("{}", x.name().unwrap()))
}
```
This goes through all the windows, finds the one that's owned by `Spotify.exe` and prints the names of all the windows they have.
It would be nice to be able to find all the windows of a specific process so I don't have to go through _every_ window but I couldn't find anything about that (tell me if you do end up finding anything about that).

Note that Spotify, for me, seems to occasionally have a few blank window titles (sometimes it does, sometimes it doesn't), so you should make sure to filter those out.

This only supports Windows for now and I'll look into Linux support in the coming week.

**Comment by HiruNya** [comment]
> 
> 
> ^^ also maybe publish to crates?

I've considered publishing this to crates.io but I feel very unsure about the current API so I ended up never doing it.
I might bump the version of this crate up to v0.2 and publish it on crates.io after I complete this issue.

**Comment by Milo123459** [comment]
Great! Have you got a discord server for example where we can chat? I'd love to help.

**Comment by Milo123459** [comment]
> Sorry, I had a busy week and only managed to allocate some time for this tonight.
> 
> I made a quick minimal version of this in the [process-support](https://github.com/HiruNya/window_titles/tree/process-support?rgh-link-date=2021-05-15T12%3A29%3A29Z) branch.
> 
> This should support something like this:
> 
> ```rust
> use window_titles::{Connection, ConnectionTrait};
> 
> fn main() {
> 	let connection = Connection::new().unwrap();
> 	connection.windows().into_iter().filter(|w| w.process().name() == "Spotify.exe")
> 		.for_each(|x| println!("{}", x.name().unwrap()))
> }
> ```
> 
> This goes through all the windows, finds the one that's owned by `Spotify.exe` and prints the names of all the windows they have.
> It would be nice to be able to find all the windows of a specific process so I don't have to go through _every_ window but I couldn't find anything about that (tell me if you do end up finding anything about that).
> 
> Note that Spotify, for me, seems to occasionally have a few blank window titles (sometimes it does, sometimes it doesn't), so you should make sure to filter those out.
> 
> This only supports Windows for now and I'll look into Linux support in the coming week.

Oh my, amazing! Thanks!

**Comment by Milo123459** [comment]
Oh and, from my understanding, if you find the PID of the spotify process you can see, get the PID from that, then get the title of that window, it'd be faster. Right now it is taking around 553ms to do it, and I'm making a PR for starship, adding a spotify module so it needs to be relatively fast. I think my approach, from my understanding, should be faster then looping over every process.
Other then that, works like a charm.

**Comment by Milo123459** [comment]
(Sorry for spamming)

Image example:
![img](https://salvage.is-inside.me/WvyIjHcZ.png)

**Comment by HiruNya** [comment]
A starship plugin seems like a really interesting use case!

Are you able to save state? or would it be a full execution every time?

I've been trying to time different implementations and currently the original version I posted took 9ms on my pc.

I then tried this (which I believe is what you were saying)
```rust
    let process = connection.processes().into_iter()
		.filter(|p| p.name() == "Spotify.exe")
		.nth(0)
		.expect("Could not find a running instance of `Spotify.exe`");
	let window = connection.windows().into_iter()
		.filter(|w| w.process() == process)
		.filter_map(|w| w.name().ok())
		.filter(|n| n.len() > 0)
		.nth(0)
		.expect("Could not find a window owned by the spotify process");
	println!("{}", window);
```
This took 12ms which went against what I was expecting (I was expecting it to be faster).
My guess is that iterating through all the processes might be much slower than simply looking through all the windows? Not sure.

Lastly, I tried a situation where you could theoretically store state and thus store the window id but this also took around 9ms.
```rust
	use window_titles::windows::Window;
	use winapi::shared::windef::HWND;
	let window = 0x40278 as HWND;
	println!("{}", Window(window).name().unwrap());
```
I would've thought this would have been the quickest considering there's absolutely no iteration at all.

At this point I'm wondering if I'm just measuring commands wrong (I'm not used to Windows unfortunately).

**Comment by HiruNya** [comment]
> 
> 
> Great! Have you got a discord server for example where we can chat? I'd love to help.

I don't but my Discord handle is `Hiru#4571` or you can contact me via email at `hiru@hiru.dev`.

**Comment by Milo123459** [comment]
Sent you a friend request!

**Comment by Milo123459** [comment]
> A starship plugin seems like a really interesting use case!
> 
> Are you able to save state? or would it be a full execution every time?
> 
> I've been trying to time different implementations and currently the original version I posted took 9ms on my pc.
> 
> I then tried this (which I believe is what you were saying)
> 
> ```rust
>     let process = connection.processes().into_iter()
> 		.filter(|p| p.name() == "Spotify.exe")
> 		.nth(0)
> 		.expect("Could not find a running instance of `Spotify.exe`");
> 	let window = connection.windows().into_iter()
> 		.filter(|w| w.process() == process)
> 		.filter_map(|w| w.name().ok())
> 		.filter(|n| n.len() > 0)
> 		.nth(0)
> 		.expect("Could not find a window owned by the spotify process");
> 	println!("{}", window);
> ```
> 
> This took 12ms which went against what I was expecting (I was expecting it to be faster).
> My guess is that iterating through all the processes might be much slower than simply looking through all the windows? Not sure.
> 
> Lastly, I tried a situation where you could theoretically store state and thus store the window id but this also took around 9ms.
> 
> ```rust
> 	use window_titles::windows::Window;
> 	use winapi::shared::windef::HWND;
> 	let window = 0x40278 as HWND;
> 	println!("{}", Window(window).name().unwrap());
> ```
> 
> I would've thought this would have been the quickest considering there's absolutely no iteration at all.
> 
> At this point I'm wondering if I'm just measuring commands wrong (I'm not used to Windows unfortunately).

I think caching is better, or store state or whatever.


And rust security is flagging this as a vulnerability. Any ideas?
